### ISSUE TITLE
bug: Download Failed

### ISSUE THREAD

**Issue by pizzapanther** [Cap-go/capacitor-updater#258]
## Bug Report

```
Device: 4490bd2f-6058-456d-bf08-e38819cefaeb
│
■  Your bundle has failed to download on your device.
│
■  Please check if you have network connection and try again
```

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/ios: 5.3.0

Installed Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/ios: 5.3.0

```

### Plugin Version
```
 OS: #31~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Aug 16 13:45:26 UTC 2

 Installed Dependencies:

   @capgo/cli: 3.13.14
   @capgo/capacitor-updater: ^5.2.32


✓ Latest Dependencies:


   @capgo/cli: 3.13.14
   @capgo/capacitor-updater: 5.2.32


```

### context(s)
```md
ManualModel: false
AutoMode: true
CapgoCloud: true
OnPremise: false
```

### Platform(s)

Android

### Current Behavior

Download always fails

### Expected Behavior

download works

### Other Technical Details

`npm --version` output: 9.6.7

`node --version` output: v18.17.1

### Additional Context

Downloads always fail. Anyway to know why? I reduced the bundle size to 3mb and it still fails.

**Comment by facuim** [comment]
Hi! I got "same issue" in manual mode and self host.
Mi zip size is ~15mb, with the index.html and only assets folder

my logcat:

```
Notifying listeners for event download
2023-09-01 00:19:03.565 21577-21577 Capacitor/Console       com.SatoshiTango.SatoshiTango        I  File: http://localhost/main.js - Line 330 - Msg: DOWNLOAD {"percent":71,"bundle":{"id":"6y6oRiWJEc","version":"4.6.6","downloaded":"2023-09-01T03:19:01.020+0000","checksum":"","status":"downloading"}}
2023-09-01 00:19:03.566 21577-21577 Capacitor/Console       com.SatoshiTango.SatoshiTango        I  File: http://localhost/main.js - Line 333 - Msg: DOWNLOAD {"percent":71,"bundle":{"id":"6y6oRiWJEc","version":"4.6.6","downloaded":"2023-09-01T03:19:01.020+0000","checksum":"","status":"downloading"}}
2023-09-01 00:19:03.566 21577-21577 Capacitor/Console       com.SatoshiTango.SatoshiTango        I  File: http://localhost/main.js - Line 330 - Msg: DOWNLOAD {"percent":75,"bundle":{"id":"6y6oRiWJEc","version":"4.6.6","downloaded":"2023-09-01T03:19:01.020+0000","checksum":"","status":"downloading"}}
2023-09-01 00:19:03.566 21577-21577 Capacitor/Console       com.SatoshiTango.SatoshiTango        I  File: http://localhost/main.js - Line 333 - Msg: DOWNLOAD {"percent":75,"bundle":{"id":"6y6oRiWJEc","version":"4.6.6","downloaded":"2023-09-01T03:19:01.020+0000","checksum":"","status":"downloading"}}
2023-09-01 00:19:03.566 21577-22683 Capacitor/...aterPlugin com.SatoshiTango.SatoshiTango        V  Notifying listeners for event download
2023-09-01 00:19:03.567 21577-22683 System.err              com.SatoshiTango.SatoshiTango        W  java.io.FileNotFoundException: Source file not found: /data/user/0/com.SatoshiTango.SatoshiTango/files/rcC3eIOsWp
2023-09-01 00:19:03.567 21577-22683 System.err              com.SatoshiTango.SatoshiTango        W  	at ee.forgr.capacitor_updater.CapacitorUpdater.flattenAssets(CapacitorUpdater.java:237)
2023-09-01 00:19:03.567 21577-22683 System.err              com.SatoshiTango.SatoshiTango        W  	at ee.forgr.capacitor_updater.CapacitorUpdater.finishDownload(CapacitorUpdater.java:343)
2023-09-01 00:19:03.567 21577-22683 System.err              com.SatoshiTango.SatoshiTango        W  	at ee.forgr.capacitor_updater.CapacitorUpdater.download(CapacitorUpdater.java:595)
2023-09-01 00:19:03.567 21577-22683 System.err              com.SatoshiTango.SatoshiTango        W  	at ee.forgr.capacitor_updater.CapacitorUpdaterPlugin.lambda$download$6(CapacitorUpdaterPlugin.java:474)
2023-09-01 00:19:03.567 21577-22683 System.err              com.SatoshiTango.SatoshiTango        W  	at ee.forgr.capacitor_updater.CapacitorUpdaterPlugin.$r8$lambda$GU2SWHxEaoMvUM2I-J3PVz71r00(Unknown Source:0)
2023-09-01 00:19:03.567 21577-22683 System.err              com.SatoshiTango.SatoshiTango        W  	at ee.forgr.capacitor_updater.CapacitorUpdaterPlugin$$ExternalSyntheticLambda2.run(Unknown Source:12)
2023-09-01 00:19:03.567 21577-22683 System.err              com.SatoshiTango.SatoshiTango        W  	at ee.forgr.capacitor_updater.CapacitorUpdaterPlugin.lambda$startNewThread$0(CapacitorUpdaterPlugin.java:93)
2023-09-01 00:19:03.567 21577-21577 Capacitor/Console       com.SatoshiTango.SatoshiTango        I  File: http://localhost/main.js - Line 330 - Msg: DOWNLOAD {"percent":91,"bundle":{"id":"6y6oRiWJEc","version":"4.6.6","downloaded":"2023-09-01T03:19:01.020+0000","checksum":"","status":"downloading"}}
2023-09-01 00:19:03.567 21577-22683 System.err              com.SatoshiTango.SatoshiTango        W  	at ee.forgr.capacitor_updater.CapacitorUpdaterPlugin$$ExternalSyntheticLambda3.run(Unknown Source:4)
2023-09-01 00:19:03.567 21577-22683 System.err              com.SatoshiTango.SatoshiTango        W  	at java.lang.Thread.run(Thread.java:1012)
2023-09-01 00:19:03.568 21577-22683 Capacitor/...aterPlugin com.SatoshiTango.SatoshiTango        V  Notifying listeners for event downloadFailed
2023-09-01 00:19:03.569 21577-22683 Capacitor-updater       com.SatoshiTango.SatoshiTango        D  Storing info for bundle [6y6oRiWJEc] {"id":"6y6oRiWJEc","version":"4.6.6","downloaded":"2023-09-01T03:19:03.568+0000","checksum":"","status":"pending"}
2023-09-01 00:19:03.571 21577-21577 Capacitor/Console       com.SatoshiTango.SatoshiTango        I  File: http://localhost/main.js - Line 333 - Msg: DOWNLOAD {"percent":91,"bundle":{"id":"6y6oRiWJEc","version":"4.6.6","downloaded":"2023-09-01T03:19:01.020+0000","checksum":"","status":"downloading"}}
2023-09-01 00:19:03.573 21577-21577 Capacitor/Console       com.SatoshiTango.SatoshiTango        I  File: http://localhost/main.js - Line 339 - Msg: DOWNLOAD FAILED {"version":"builtin"}
2023-09-01 00:19:03.574 21577-21577 Capacitor/Console       com.SatoshiTango.SatoshiTango        I  File: http://localhost/main.js - Line 345 - Msg: FACU {"id":"6y6oRiWJEc","version":"4.6.6","downloaded":"2023-09-01T03:19:03.568+0000","checksum":"","status":"pending"}
2023-09-01 00:19:03.575 21577-21577 Capacitor/Plugin        com.SatoshiTango.SatoshiTango        V  To native (Capacitor plugin): callbackId: 83704196, pluginId: CapacitorUpdater, methodName: set
2023-09-01 00:19:03.575 21577-21577 Capacitor               com.SatoshiTango.SatoshiTango        V  callback: 83704196, pluginId: CapacitorUpdater, methodName: set, methodData: {"id":"6y6oRiWJEc"}
```

**Comment by pizzapanther** [comment]
switched to self hosted and got it working
