### ISSUE TITLE
bug: App crashing after closing due to an `AssertionError` thrown by the plugin in `isMainActivity`

### ISSUE THREAD

**Issue by therealabdi2** [Cap-go/capacitor-updater#477]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

```

### context(s)

```md
ManualModel: true
AutoMode: false
CapgoCloud: false
OnPremise: false
```

### Platform(s)

Android

### Current Behavior

When opening and then closing the app, the following error appears in the logs:

 FATAL EXCEPTION: main
                                                                                                    Process: pk.edu.niete.stage, PID: 17035
                                                                                                    java.lang.AssertionError
                                                                                                    	at ee.forgr.capacitor_updater.CapacitorUpdaterPlugin.isMainActivity(CapacitorUpdaterPlugin.java:1593)
                                                                                                    	at ee.forgr.capacitor_updater.CapacitorUpdaterPlugin.handleOnStop(CapacitorUpdaterPlugin.java:1620)
                                                                                                    	at com.getcapacitor.Bridge.onStop(Bridge.java:1335)
                                                                                                    	at com.getcapacitor.BridgeActivity.onStop(BridgeActivity.java:117)
                                                                                                    	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1497)
                                                                                                    	at android.app.Activity.performStop(Activity.java:8280)
                                                                                                    	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5158)
                                                                                                    	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5138)
                                                                                                    	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5203)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:234)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2215)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:346)
                                                                                                    	at android.os.Looper.loop(Looper.java:475)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7889)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)

### Expected Behavior

The app should not crash when closed.

### Additional Context

This crash does not impact user experience directly but is causing excessive error logs in Firebase Crashlytics. The issue seems to stem from this line in the code:

` assert runningTask.topActivity != null;`

```
private boolean isMainActivity() {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) {
      return false;
    }
    try {
      Context mContext = this.getContext();
      ActivityManager activityManager =
        (ActivityManager) mContext.getSystemService(Context.ACTIVITY_SERVICE);
      List<ActivityManager.AppTask> runningTasks =
        activityManager.getAppTasks();
      if (runningTasks.isEmpty()) {
        return false;
      }
      ActivityManager.RecentTaskInfo runningTask = runningTasks
        .get(0)
        .getTaskInfo();
      String className = Objects.requireNonNull(
        runningTask.baseIntent.getComponent()
      ).getClassName();
      assert runningTask.topActivity != null;
      String runningActivity = runningTask.topActivity.getClassName();
      return className.equals(runningActivity);
    } catch (NullPointerException e) {
      return false;
    }
  }
```

Changing the isMainActivity method as shown below prevents the crash from occurring when the app is closed:

` String runningActivity = runningTask.topActivity != null ? runningTask.topActivity.getClassName() : null;`

```
private boolean isMainActivity() {
  if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) {
    return false;
  }
  try {
    Context mContext = this.getContext();
    ActivityManager activityManager =
      (ActivityManager) mContext.getSystemService(Context.ACTIVITY_SERVICE);
    List<ActivityManager.AppTask> runningTasks = activityManager.getAppTasks();
    if (runningTasks.isEmpty()) {
      return false;
    }
    ActivityManager.RecentTaskInfo runningTask = runningTasks.get(0).getTaskInfo();
    String className = Objects.requireNonNull(runningTask.baseIntent.getComponent()).getClassName();
    String runningActivity = runningTask.topActivity != null ? runningTask.topActivity.getClassName() : null;
    return className.equals(runningActivity);
  } catch (NullPointerException e) {
    return false;
  }
}

```

The issue also occurs in version 5 of the plugin which we are using.

**Comment by riderx** [comment]
This has been fixed, on last version thanks for the report

**Comment by therealabdi2** [comment]
@riderx any chance you could release it for capacitor v5 as well?
